# **Numpy**

## Arrays


In [ ]:
import numpy as np
arr = np.arange(10000)
print(arr)
print(arr[:10])
print(len(arr))

[   0    1    2 ... 9997 9998 9999]
[0 1 2 3 4 5 6 7 8 9]
10000


## Array vs List

In [ ]:
arr = np.arange(10000)
arr_list = list(range(10000))
%time a = [x * 10 for x in arr_list]
%time b = arr * 10

CPU times: user 980 µs, sys: 0 ns, total: 980 µs
Wall time: 988 µs
CPU times: user 171 µs, sys: 0 ns, total: 171 µs
Wall time: 341 µs


It takes less time to multiply an array with a number than list.

## Multidimensional Arrays

In [ ]:
arr = np.random.randn(4, 4)
print(arr)
arr3 = arr * 3
print(arr+arr3)

[[ 0.12311313 -0.67620328 -0.1654305   0.92236121]
 [ 0.45400348 -0.8791964  -0.87491064 -0.61639908]
 [-0.17114207 -0.35080177 -1.63113584  1.31311746]
 [-0.62049418  0.80991209 -1.21224645 -0.70434023]]
[[ 0.49245253 -2.70481312 -0.66172202  3.68944485]
 [ 1.81601394 -3.5167856  -3.49964256 -2.46559634]
 [-0.68456826 -1.40320707 -6.52454335  5.25246986]
 [-2.48197671  3.23964836 -4.84898581 -2.81736092]]


Choosing specific element
 - choosing element from first row third column

In [ ]:
arr = np.random.randn(4, 4)
print(arr)
arr[0, 2]

[[-0.3643231   1.02820344  0.31377921  0.35210323]
 [ 0.71602659  0.22362449  1.79153332 -0.10912512]
 [ 1.01861319 -0.10570164  0.90254266 -0.64081462]
 [ 0.42565285  0.96703767  0.6418268  -0.66072265]]


0.3137792128233644

Slicing
 - first two rows


In [ ]:
arr = np.random.randn(4, 4)
print(arr)
arr[0:2]

[[ 1.23370619  0.87626386 -1.49935568 -1.15860734]
 [ 0.50530022 -0.31554307 -1.10837917  0.43157208]
 [-0.4075795   0.93644147 -1.34000096 -0.57897078]
 [ 0.35395266  2.18620087  1.48519641  0.34351799]]


array([[ 1.23370619,  0.87626386, -1.49935568, -1.15860734],
       [ 0.50530022, -0.31554307, -1.10837917,  0.43157208]])

 - middle section

In [ ]:
arr = np.random.randn(4, 4)
print(arr)
arr[0:2, 1:3]

[[-0.01017628  0.92225563  0.7169816   0.83578564]
 [ 0.0222195   0.59016986  0.02950137 -1.01142051]
 [ 0.30292535  1.62683977  0.66294996  0.9493093 ]
 [ 0.94066333  0.85374     0.70963291 -1.12857818]]


array([[0.92225563, 0.7169816 ],
       [0.59016986, 0.02950137]])

# **Pandas**

Pandas defines two majore data structures, Series and DataFrame. A Series is a one-dimensional array-like object containing a sequence of values.

In [ ]:
import pandas as pd
pd.Series(['a', 'b', 'c', 'd', 'e'])

0    a
1    b
2    c
3    d
4    e
dtype: object

Series can also have indexes or labels attached to each value (where they are then almost similar to a dict)

In [ ]:
ser = pd.Series(['a', 'b', 'c', 'd', 'e'], index=['foo', 'bar', 'more', 'note', 'extra'])
ser

foo      a
bar      b
more     c
note     d
extra    e
dtype: object

Now you can access each object using the dot notation or brackets
 - ser.foo
 - ser['foo']

In [ ]:
import pandas as pd
ser = pd.Series(['a', 'b', 'c', 'd', 'e'], index=['foo', 'bar', 'more', 'note', 'extra'])
ser.to_dict()

{'foo': 'a', 'bar': 'b', 'more': 'c', 'note': 'd', 'extra': 'e'}